package rs.pedjaapps.tvshowtracker.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ACTOR.
 */
public class Actor {

    private Long id;
    private String name;
    private String character;
    private String image;
    private long show_id;

    public Actor() {
    }

    public Actor(Long id) {
        this.id = id;
    }

    public Actor(Long id, String name, String character, String image, long show_id) {
        this.id = id;
        this.name = name;
        this.character = character;
        this.image = image;
        this.show_id = show_id;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getCharacter() {
        return character;
    }

    public void setCharacter(String character) {
        this.character = character;
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    public long getShow_id() {
        return show_id;
    }

    public void setShow_id(long show_id) {
        this.show_id = show_id;
    }

}
