package rs.pedjaapps.tvshowtracker.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table IMAGE.
 */
public class Image {

    private Long id;
    private String poster;
    private String fanart;
    private String banner;

    public Image() {
    }

    public Image(Long id) {
        this.id = id;
    }

    public Image(Long id, String poster, String fanart, String banner) {
        this.id = id;
        this.poster = poster;
        this.fanart = fanart;
        this.banner = banner;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getPoster() {
        return poster;
    }

    public void setPoster(String poster) {
        this.poster = poster;
    }

    public String getFanart() {
        return fanart;
    }

    public void setFanart(String fanart) {
        this.fanart = fanart;
    }

    public String getBanner() {
        return banner;
    }

    public void setBanner(String banner) {
        this.banner = banner;
    }

}
