package rs.pedjaapps.trakttvandroid;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import rs.pedjaapps.trakttvandroid.User;
import rs.pedjaapps.trakttvandroid.Connection;

import rs.pedjaapps.trakttvandroid.UserDao;
import rs.pedjaapps.trakttvandroid.ConnectionDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig connectionDaoConfig;

    private final UserDao userDao;
    private final ConnectionDao connectionDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        connectionDaoConfig = daoConfigMap.get(ConnectionDao.class).clone();
        connectionDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        connectionDao = new ConnectionDao(connectionDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(Connection.class, connectionDao);
    }
    
    public void clear() {
        userDaoConfig.getIdentityScope().clear();
        connectionDaoConfig.getIdentityScope().clear();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public ConnectionDao getConnectionDao() {
        return connectionDao;
    }

}
