package rs.pedjaapps.trakttvandroid;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table user.
 */
public class User {

    private Long id;
    /** Not-null value. */
    private String username;
    private String full_name;
    private String gender;
    private String age;
    private String location;
    private String about;
    private Long joined;
    private Long last_login;
    private String avatar;
    private String url;
    private Boolean vip;
    private String timezone;
    private Boolean use_24;
    private Boolean protected;
    private String ratings_mode;
    private Boolean show_badges;
    private Boolean show_spoilers;
    private String watching;
    private String watched;

    public User() {
    }

    public User(Long id) {
        this.id = id;
    }

    public User(Long id, String username, String full_name, String gender, String age, String location, String about, Long joined, Long last_login, String avatar, String url, Boolean vip, String timezone, Boolean use_24, Boolean protected, String ratings_mode, Boolean show_badges, Boolean show_spoilers, String watching, String watched) {
        this.id = id;
        this.username = username;
        this.full_name = full_name;
        this.gender = gender;
        this.age = age;
        this.location = location;
        this.about = about;
        this.joined = joined;
        this.last_login = last_login;
        this.avatar = avatar;
        this.url = url;
        this.vip = vip;
        this.timezone = timezone;
        this.use_24 = use_24;
        this.protected = protected;
        this.ratings_mode = ratings_mode;
        this.show_badges = show_badges;
        this.show_spoilers = show_spoilers;
        this.watching = watching;
        this.watched = watched;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getUsername() {
        return username;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUsername(String username) {
        this.username = username;
    }

    public String getFull_name() {
        return full_name;
    }

    public void setFull_name(String full_name) {
        this.full_name = full_name;
    }

    public String getGender() {
        return gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    public String getAge() {
        return age;
    }

    public void setAge(String age) {
        this.age = age;
    }

    public String getLocation() {
        return location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    public String getAbout() {
        return about;
    }

    public void setAbout(String about) {
        this.about = about;
    }

    public Long getJoined() {
        return joined;
    }

    public void setJoined(Long joined) {
        this.joined = joined;
    }

    public Long getLast_login() {
        return last_login;
    }

    public void setLast_login(Long last_login) {
        this.last_login = last_login;
    }

    public String getAvatar() {
        return avatar;
    }

    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public Boolean getVip() {
        return vip;
    }

    public void setVip(Boolean vip) {
        this.vip = vip;
    }

    public String getTimezone() {
        return timezone;
    }

    public void setTimezone(String timezone) {
        this.timezone = timezone;
    }

    public Boolean getUse_24() {
        return use_24;
    }

    public void setUse_24(Boolean use_24) {
        this.use_24 = use_24;
    }

    public Boolean getProtected() {
        return protected;
    }

    public void setProtected(Boolean protected) {
        this.protected = protected;
    }

    public String getRatings_mode() {
        return ratings_mode;
    }

    public void setRatings_mode(String ratings_mode) {
        this.ratings_mode = ratings_mode;
    }

    public Boolean getShow_badges() {
        return show_badges;
    }

    public void setShow_badges(Boolean show_badges) {
        this.show_badges = show_badges;
    }

    public Boolean getShow_spoilers() {
        return show_spoilers;
    }

    public void setShow_spoilers(Boolean show_spoilers) {
        this.show_spoilers = show_spoilers;
    }

    public String getWatching() {
        return watching;
    }

    public void setWatching(String watching) {
        this.watching = watching;
    }

    public String getWatched() {
        return watched;
    }

    public void setWatched(String watched) {
        this.watched = watched;
    }

}
