package rs.pedjaapps.tvshowtracker.model;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
import android.os.Parcel;
import android.os.Parcelable;
// KEEP INCLUDES END
/**
 * Entity mapped to table ACTOR.
 */
public class Actor implements Parcelable {

    private Long id;
    private String name;
    private String character;
    private String image;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Actor() {
    }

    public Actor(Long id) {
        this.id = id;
    }

    public Actor(Long id, String name, String character, String image, long show_id) {
        this.id = id;
        this.name = name;
        this.character = character;
        this.image = image;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getCharacter() {
        return character;
    }

    public void setCharacter(String character) {
        this.character = character;
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    // KEEP METHODS - put your custom methods here
    @Override
    public int describeContents()
    {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags)
    {
        dest.writeValue(this.id);
        dest.writeString(this.name);
        dest.writeString(this.character);
        dest.writeString(this.image);
    }

    private Actor(Parcel in)
    {
        this.id = (Long) in.readValue(Long.class.getClassLoader());
        this.name = in.readString();
        this.character = in.readString();
        this.image = in.readString();
    }

    public static Creator<Actor> CREATOR = new Creator<Actor>()
    {
        public Actor createFromParcel(Parcel source)
        {
            return new Actor(source);
        }

        public Actor[] newArray(int size)
        {
            return new Actor[size];
        }
    };
    // KEEP METHODS END

}
