package rs.pedjaapps.tvshowtracker.model;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
import android.os.Parcel;
import android.os.Parcelable;
// KEEP INCLUDES END
/**
 * Entity mapped to table EPISODE.
 */
public class Episode implements Parcelable {

    private Long id;
    private int season;
    private int episode;
    private Integer tvdb_id;
    private String title;
    private String overview;
    private Long first_aired;
    private String url;
    private String screen;
    private Integer rating;
    private Integer votes;
    private Integer loved;
    private Integer hated;
    private boolean watched;
    private long show_id;

    // KEEP FIELDS - put your custom fields here
    private boolean isEpisode;//episode or season, for adapter
    private String showTitle;
    private long airsIn;//hours
    // KEEP FIELDS END

    public Episode() {
    }

    public Episode(Long id) {
        this.id = id;
    }

    public Episode(Long id, int season, int episode, Integer tvdb_id, String title, String overview, Long first_aired, String url, String screen, Integer rating, Integer votes, Integer loved, Integer hated, boolean watched, long show_id) {
        this.id = id;
        this.season = season;
        this.episode = episode;
        this.tvdb_id = tvdb_id;
        this.title = title;
        this.overview = overview;
        this.first_aired = first_aired;
        this.url = url;
        this.screen = screen;
        this.rating = rating;
        this.votes = votes;
        this.loved = loved;
        this.hated = hated;
        this.watched = watched;
        this.show_id = show_id;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getSeason() {
        return season;
    }

    public void setSeason(int season) {
        this.season = season;
    }

    public int getEpisode() {
        return episode;
    }

    public void setEpisode(int episode) {
        this.episode = episode;
    }

    public Integer getTvdb_id() {
        return tvdb_id;
    }

    public void setTvdb_id(Integer tvdb_id) {
        this.tvdb_id = tvdb_id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getOverview() {
        return overview;
    }

    public void setOverview(String overview) {
        this.overview = overview;
    }

    public Long getFirst_aired() {
        return first_aired;
    }

    public void setFirst_aired(Long first_aired) {
        this.first_aired = first_aired;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getScreen() {
        return screen;
    }

    public void setScreen(String screen) {
        this.screen = screen;
    }

    public Integer getRating() {
        return rating;
    }

    public void setRating(Integer rating) {
        this.rating = rating;
    }

    public Integer getVotes() {
        return votes;
    }

    public void setVotes(Integer votes) {
        this.votes = votes;
    }

    public Integer getLoved() {
        return loved;
    }

    public void setLoved(Integer loved) {
        this.loved = loved;
    }

    public Integer getHated() {
        return hated;
    }

    public void setHated(Integer hated) {
        this.hated = hated;
    }

    public boolean getWatched() {
        return watched;
    }

    public void setWatched(boolean watched) {
        this.watched = watched;
    }

    public long getShow_id() {
        return show_id;
    }

    public void setShow_id(long show_id) {
        this.show_id = show_id;
    }

    // KEEP METHODS - put your custom methods here
    @Override
    public int describeContents()
    {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags)
    {
        dest.writeValue(this.id);
        dest.writeValue(this.season);
        dest.writeValue(this.episode);
        dest.writeValue(this.tvdb_id);
        dest.writeString(this.title);
        dest.writeString(this.overview);
        dest.writeValue(this.first_aired);
        dest.writeString(this.url);
        dest.writeString(this.screen);
        dest.writeValue(this.rating);
        dest.writeValue(this.votes);
        dest.writeValue(this.loved);
        dest.writeValue(this.hated);
        dest.writeByte(watched ? (byte) 1 : (byte) 0);
        dest.writeLong(this.show_id);
    }

    private Episode(Parcel in)
    {
        this.id = (Long) in.readValue(Long.class.getClassLoader());
        this.season = (Integer) in.readValue(Integer.class.getClassLoader());
        this.episode = (Integer) in.readValue(Integer.class.getClassLoader());
        this.tvdb_id = (Integer) in.readValue(Integer.class.getClassLoader());
        this.title = in.readString();
        this.overview = in.readString();
        this.first_aired = (Long) in.readValue(Long.class.getClassLoader());
        this.url = in.readString();
        this.screen = in.readString();
        this.rating = (Integer) in.readValue(Integer.class.getClassLoader());
        this.votes = (Integer) in.readValue(Integer.class.getClassLoader());
        this.loved = (Integer) in.readValue(Integer.class.getClassLoader());
        this.hated = (Integer) in.readValue(Integer.class.getClassLoader());
        this.watched = in.readByte() != 0;
        this.show_id = in.readLong();
    }

    public static Creator<Episode> CREATOR = new Creator<Episode>()
    {
        public Episode createFromParcel(Parcel source)
        {
            return new Episode(source);
        }

        public Episode[] newArray(int size)
        {
            return new Episode[size];
        }
    };

    public boolean isEpisode()
    {
        return isEpisode;
    }

    public void setEpisode(boolean isEpisode)
    {
        this.isEpisode = isEpisode;
    }

    public boolean isWatched()
    {
        return watched;
    }

    public String getShowTitle()
    {
        return showTitle;
    }

    public void setShowTitle(String showTitle)
    {
        this.showTitle = showTitle;
    }

    public long getAirsIn()
    {
        return airsIn;
    }

    public void setAirsIn(long airsIn)
    {
        this.airsIn = airsIn;
    }
    // KEEP METHODS END

}
