package rs.pedjaapps.tvshowtracker.model;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
import android.os.Parcel;
import android.os.Parcelable;
// KEEP INCLUDES END
/**
 * Entity mapped to table GENRE.
 */
public class Genre implements Parcelable {

    private Long id;
    private String name;
    private long show_id;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Genre() {
    }

    public Genre(Long id) {
        this.id = id;
    }

    public Genre(Long id, String name, long show_id) {
        this.id = id;
        this.name = name;
        this.show_id = show_id;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public long getShow_id() {
        return show_id;
    }

    public void setShow_id(long show_id) {
        this.show_id = show_id;
    }

    // KEEP METHODS - put your custom methods here
    @Override
    public int describeContents()
    {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags)
    {
        dest.writeValue(this.id);
        dest.writeString(this.name);
        dest.writeLong(this.show_id);
    }

    private Genre(Parcel in)
    {
        this.id = (Long) in.readValue(Long.class.getClassLoader());
        this.name = in.readString();
        this.show_id = in.readLong();
    }

    public static Creator<Genre> CREATOR = new Creator<Genre>()
    {
        public Genre createFromParcel(Parcel source)
        {
            return new Genre(source);
        }

        public Genre[] newArray(int size)
        {
            return new Genre[size];
        }
    };
    // KEEP METHODS END

}
